name: Learning actions

on: 
  push:
    branches: [ "main" ]
  
jobs: 
  build-and-test:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      
      - name: Install dependcies
        run: npm install 
      
      - name: Build the app
        run: npm run build
        